import { WebviewRouteEnum } from '@/constants/enums';
import { LESSON_ROUTE, PROFILE_ROUTE, VERSION_INFO_SCREEN, LOCAL_NOTIFICATION_SCREEN } from '@/navigation/config/routes';

export const drawerData = [
  {
    id: 0,
    icon: '',
    name: 'マイページ',
    url: PROFILE_ROUTE.MY_PAGE,
    isNavInApp: true,
  },
  {
    id: 1,
    icon: '',
    name: 'レッスン一覧',
    url: LESSON_ROUTE.LESSON_LIST,
    isNavInApp: true,
  },
  {
    id: 2,
    icon: '',
    name: 'テスト一覧',
    url: WebviewRouteEnum.test,
  },
  {
    id: 3,
    icon: '',
    name: 'つぶやき応用練習[a]',
    url: WebviewRouteEnum.advancedA,
  },
  {
    id: 4,
    icon: '',
    name: 'つぶやき応用練習[b]',
    url: WebviewRouteEnum.advancedB,
  },
  {
    id: 5,
    icon: '',
    name: '会議の英語',
    url: WebviewRouteEnum.meeting,
  },
  {
    id: 6,
    icon: '',
    name: 'レッスン・テスト記録',
    url: WebviewRouteEnum.record,
  },
  {
    id: 7,
    icon: '',
    name: 'マイチャンク',
    url: WebviewRouteEnum.chunk,
  },
  {
    id: 8,
    icon: '',
    name: '学習ガイド',
    url: WebviewRouteEnum.navigate2,
  },
  {
    id: 9,
    icon: '',
    name: 'よくある質問',
    url: WebviewRouteEnum.faq,
  },
  {
    id: 10,
    icon: '',
    name: 'セミナー動画',
    url: WebviewRouteEnum.seminar,
  },
  {
    id: 11,
    icon: '',
    name: 'プレゼント教材',
    url: WebviewRouteEnum.present,
  },
  {
    id: 12,
    icon: '',
    name: '紹介プログラム',
    url: WebviewRouteEnum.referral,
  },
  {
    id: 13,
    icon: '',
    name: '利用者インタビュー',
    url: WebviewRouteEnum.interview,
  },
  {
    id: 14,
    icon: '',
    name: '教材の特徴・メソッド',
    url: WebviewRouteEnum.navigate1,
  },
  {
    id: 15,
    icon: '',
    name: 'ダウンロード',
    url: WebviewRouteEnum.download,
  },
  {
    id: 16,
    icon: '',
    name: '各種設定',
    url: WebviewRouteEnum.setting,
  },
  {
    id: 22,
    icon: '',
    name: '通知設定',
    url: LOCAL_NOTIFICATION_SCREEN,
    isNavInApp: true,
  },
  {
    id: 17,
    icon: '',
    name: 'パスワード変更',
    url: WebviewRouteEnum.password,
  },
  {
    id: 18,
    icon: '',
    name: 'バージョン情報',
    url: VERSION_INFO_SCREEN,
    isNavInApp: true,
  },
  {
    id: 19,
    icon: '',
    name: 'チュートリアル',
    url: PROFILE_ROUTE.WALK_THROUGH_PAGE,
    isNavInApp: true,
  },
  {
    id: 20,
    icon: '',
    name: 'ログアウト',
    url: '',
    isLogout: true,
  },
  {
    id: 21,
    icon: '',
    name: '開発用画面',
    url: 'Debug',
    isNavInApp: true,
  },
];
