const AUTHENTICATE_ROUTE = {
  LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
  FORGOT_PASS: '@AUTHENTICATE_ROUTE/FORGOT_PASS',
  SIGN_UP: '@AUTHENTICATE_ROUTE/SIGN_UP',
  TERMS: '@AUTHENTICATE_ROUTE/TERMS',
};

const LESSON_ROUTE = {
  LESSON_STACK: '@LESSON_ROUTE/LESSON_STACK',
  LESSON_LIST: '@LESSON_ROUTE/LESSON_LIST',
  LESSON_LISTING: '@LESSON_ROUTE/LESSON_LISTING',
  LESSON_DETAIL: '@LESSON_ROUTE/LESSON_DETAIL'
};


const PROFILE_ROUTE = {
  MY_PAGE: '@PROFILE_ROUTE/MY_PAGE',
  WALK_THROUGH_PAGE: '@PROFILE_ROUTE/WALK_THROUGH_PAGE'
};

const DRAWER_ROUTE = {
  DRAWER_STACK: '@DRAWER_ROUTE/DRAWER_STACK'
};

const WEBVIEW_SCREEN = 'WEBVIEW_SCREEN';
const VERSION_INFO_SCREEN = 'VERSION_INFO_SCREEN';
const LOCAL_NOTIFICATION_SCREEN = 'LOCAL_NOTIFICATION_SCREEN';

export { LESSON_ROUTE, PROFILE_ROUTE, AUTHENTICATE_ROUTE, DRAWER_ROUTE, WEBVIEW_SCREEN, VERSION_INFO_SCREEN, LOCAL_NOTIFICATION_SCREEN };
